MIN_LENGTH = 1
MAX_LENGTH = 400
JSON = "JSON"
HTML = "HTML"
PLAIN = "PLAIN"
RAW = "RAW"

ENV_RESOURCE_POLICY_ID = "resource_policy_id"

IDENTIFIER_REGEX_CONDITION = r"^[A-Za-z0-9\.\-:_,=\/@]+$"
MSMQ_NAME_REGEX_CONDITION = r"^[A-Za-z0-9_\.]+$"
NAME_REGEX_CONDITION = r"^[A-Za-z0-9/\-_:,\s@\.]+$"
GROUP_NAME_REGEX_CONDITION = r"^[A-Za-z0-9_\-\s]+$"
FILE_NAME_REGEX_CONDITION = r"^[A-Za-z0-9/\-_:,\s\.]+$"
TYPE_REGEX_CONDITION = r"^[A-Za-z0-9\-_:&]+$"
RELATION_NAME_REGEX_CONDITION = r"^[A-Za-z0-9\-_]+$"
DATA_KEY_REGEX_CONDITION = r"^[a-z0-9_]+$"
ACTION_NAME_REGEX_CONDITION = r"^[A-Za-z0-9\-_\*]+$"

OPERATION_ADD = "add"
OPERATION_DELETE = "del"

DEFAULT_UPLOAD_PATH = "uploads/"
FILE = "FILE"
ENDPOINT = "ENDPOINT"


ORG = "ORG"
APPLICATION = "APP"
PROJECT = "PRJ"
TYPE = "TYPE"
NAMESPACE = "NS"

ENV_SERVICE_ID = "service_id"
ENV_SETTINGS_ID = "settings_id"
ENV_INBOUND_POLICY_ID = "inbound_policy_id"
ENV_OUTBOUND_POLICY_ID = "outbound_policy_id"

KEY_CACHE_TIMEOUT = "CACHE_TIMEOUT"

# SERVICE_CONFIG_ID FE
SERVICE_CONFIG_ID_SSO_FE = "sso_fe"

# SERVICE_CONFIG_ID API
SERVICE_CONFIG_ID_UTILS_API = "utils_api"
SERVICE_CONFIG_ID_SSO_API = "sso_api"
SERVICE_CONFIG_ID_GATEWAY_API = "gateway_api"
SERVICE_CONFIG_ID_CERTS_API = "certs_api"
SERVICE_CONFIG_ID_PERMS_API = "perms_api"
SERVICE_CONFIG_ID_REMIND_API = "remind_api"
SERVICE_CONFIG_ID_FILE_API = "file_api"
SERVICE_CONFIG_ID_ACCOUNTS_API = "accounts_api"
SERVICE_CONFIG_ID_BIND_API = "bind_api"
SERVICE_CONFIG_ID_ESP_GATEWAY_API = "esp_gateway_api"
SERVICE_CONFIG_ID_ESP_POSTMARK_API = "esp_postmark_api"


# COMMON ACTIONS
SIGNAL_CLEAR_OUTBOUND = "CLEAR_OUTBOUND"
SIGNAL_CLEAR_INBOUND = "CLEAR_INBOUND"

# TABLE SIGNALS
SIGNAL_TBL_UPSERT = "TBL_UPSERT"
