
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-11T00:50:47+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "f5896677e6e849725ef8cccea2e627f23421a548",
 "version": "3.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
