# Generated by Django 3.2.12 on 2022-02-06 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_preference_model_unique'),
        ('stoelindeling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='core.person', verbose_name='Person'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='stoelindeling.seatingplan', verbose_name='Seating plan'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='x',
            field=models.IntegerField(default=-1, verbose_name='X position'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='y',
            field=models.IntegerField(default=-1, verbose_name='Y position'),
        ),
    ]
