# Generated by Django 4.2.9 on 2024-01-11 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stoelindeling', '0006_add_managed_by_app_label'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='seatingplan',
            managers=[
            ],
        ),
    ] + [
        migrations.RunSQL(
            f"ALTER TABLE stoelindeling_{model_name} drop column if exists site_id;"
        ) for model_name  in
        [
            "seatingplan",
            "seat",
        ]
    ]

