
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-09T22:26:47+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "d644ce27a3ca69ccac682dc3aedbd35c6c1a42e2",
 "version": "1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
