
world_zone = [
    {'country': 'Usa', 'int_code': 1},
    {'country': 'United States Virgin Islands', 'int_code': 1},
    {'country': 'Guam', 'int_code': 1},
    {'country': 'Northern Mariana Islands', 'int_code': 1, },
    {'country': 'American Samoa', 'int_code': 1},
    {'country': 'Puerto Rico', 'int_code': 1},
    {'country': 'Canada', 'int_code': 1},
    {'country': 'Bahamas', 'int_code': 1},
    {'country': 'Barbados', 'int_code': 1},
    {'country': 'Anguilla', 'int_code': 1},
    {'country': 'Antigua and Barbuda', 'int_code': 1},
    {'country': 'British Virgin Islands', 'int_code': 1},
    {'country': 'Cayman Islands', 'int_code': 1},
    {'country': 'Bermuda', 'int_code': 1},
    {'country': 'Grenada', 'int_code': 1, 'phone_prefix': 473},
    {'country': 'Turks and Caicos Islands', 'int_code': 1, 'phone_prefix': 649},
    {'country': 'Jamaica', 'int_code': 1, 'phone_prefix': [658, 876]},
    {'country': 'Montserrat', 'int_code': 1, 'phone_prefix': 664},
    {'country': 'Sint Maarten', 'int_code': 1, 'phone_prefix': 721},
    {'country': 'Saint Lucia', 'int_code': 1, 'phone_prefix': 758},
    {'country': 'Dominica', 'int_code': 1, 'phone_prefix': 767},
    {'country': 'Saint Vincent and the Grenadines',
        'int_code': 1, 'phone_prefix': 784},
    {'country': 'Dominican Republic', 'int_code': 1,
        'phone_prefix': [809, 829, 849]},
    {'country': 'Trinidad and Tobago', 'int_code': 1, 'phone_prefix': 868},
    {'country': 'Saint Kitts and Nevis', 'int_code': 1, 'phone_prefix': 869},
    {'country': 'Egypt', 'int_code': 20},
    {'country': 'South Sudan', 'int_code': 211},
    {'country': 'Morocco', 'int_code': 212},
    {'country': 'Algeria', 'int_code': 213},
    {'country': 'Tunisia', 'int_code': 216},
    {'country': 'Libya', 'int_code': 218},
    {'country': 'Gambia', 'int_code': 220},
    {'country': 'Senegal', 'int_code': 221},
    {'country': 'Mauritania', 'int_code': 222},
    {'country': 'Mali', 'int_code': 223},
    {'country': 'Guinea', 'int_code': 224},
    {'country': 'Ivory Coast', 'int_code': 225},
    {'country': 'Burkina Faso', 'int_code': 226},
    {'country': 'Niger', 'int_code': 227},
    {'country': 'Togo', 'int_code': 228},
    {'country': 'Benin', 'int_code': 229},
    {'country': 'Mauritius', 'int_code': 230},
    {'country': 'Liberia', 'int_code': 231},
    {'country': 'Sierra Leone', 'int_code': 232},
    {'country': 'Ghana', 'int_code': 233},
    {'country': 'Nigeria', 'int_code': 234},
    {'country': 'Chad', 'int_code': 235},
    {'country': 'Central African Republic', 'int_code': 236},
    {'country': 'Cameroon', 'int_code': 237},
    {'country': 'Cape Verde', 'int_code': 238},
    {'country': 'Sao Tomé and Príncipe', 'int_code': 239},
    {'country': 'Equatorial Guinea', 'int_code': 240},
    {'country': 'Gabon', 'int_code': 241},
    {'country': 'Republic of the Congo', 'int_code': 242},
    {'country': 'Democratic Republic of the Congo', 'int_code': 243},
    {'country': 'Angola', 'int_code': 244},
    {'country': 'Guinea-Bissau', 'int_code': 245},
    {'country': 'British Indian Ocean Territory', 'int_code': 246},
    {'country': 'Ascension Island', 'int_code': 247},
    {'country': 'Seychelles', 'int_code': 248},
    {'country': 'Sudan', 'int_code': 249},
    {'country': 'Rwanda', 'int_code': 250},
    {'country': 'Ethiopia', 'int_code': 251},
    {'country': 'Somalia', 'int_code': 252},
    {'country': 'Djibouti', 'int_code': 253},
    {'country': 'Kenya', 'int_code': 254},
    {'country': 'Tanzania', 'int_code': 255},
    {'country': 'Uganda', 'int_code': 256},
    {'country': 'Burundi', 'int_code': 257},
    {'country': 'Mozambique', 'int_code': 258},
    {'country': 'Zambia', 'int_code': 260},
    {'country': 'Madagascar', 'int_code': 261},
    {'country': 'Reunion', 'int_code': 262},
    {'country': 'Zimbabwe', 'int_code': 263},
    {'country': 'Namibia', 'int_code': 264},
    {'country': 'Malawi', 'int_code': 265},
    {'country': 'Lesotho', 'int_code': 266},
    {'country': 'Botswana', 'int_code': 267},
    {'country': 'Eswatini', 'int_code': 268},
    {'country': 'Comoros', 'int_code': 269},
    {'country': 'South Africa', 'int_code': 27},
    {'country': 'Saint Helena', 'int_code': 290},
    {'country': 'Eritrea', 'int_code': 291},
    {'country': 'Aruba', 'int_code': 297},
    {'country': 'Faroe Islands', 'int_code': 298},
    {'country': 'Greenland', 'int_code': 299},
    {'country': 'Greece', 'int_code': 30},
    {'country': 'Netherlands', 'int_code': 31},
    {'country': 'Belgium', 'int_code': 32},
    {'country': 'France', 'int_code': 33},
    {'country': 'Spain', 'int_code': 34},
    {'country': 'Gibraltar', 'int_code': 350},
    {'country': 'Portugal', 'int_code': 351},
    {'country': 'Madeira', 'int_code': 351, 'phone_prefix': 291},
    {'country': 'Azores', 'int_code': 351, 'phone_prefix': [292, 295, 296]},
    {'country': 'Luxembourg', 'int_code': 352},
    {'country': 'Ireland', 'int_code': 353},
    {'country': 'Iceland', 'int_code': 354},
    {'country': 'Albania', 'int_code': 355},
    {'country': 'Malta', 'int_code': 356},
    {'country': 'Cyprus', 'int_code': 357},
    {'country': 'Finland', 'int_code': 358},
    {'country': 'Bulgaria', 'int_code': 359},
    {'country': 'Hungary', 'int_code': 36},
    {'country': 'Lithuania', 'int_code': 370},
    {'country': 'Latvia', 'int_code': 371},
    {'country': 'Estonia', 'int_code': 372},
    {'country': 'Moldova', 'int_code': 373},
    {'country': 'Armenia', 'int_code': 374},
    {'country': 'Belarus', 'int_code': 375},
    {'country': 'Andorra', 'int_code': 376},
    {'country': 'Monaco', 'int_code': 377},
    {'country': 'San Marino', 'int_code': 378},
    {'country': 'Vatican City', 'int_code': 379},
    {'country': 'Ukraine', 'int_code': 380},
    {'country': 'Serbia', 'int_code': 381},
    {'country': 'Montenegro', 'int_code': 382},
    {'country': 'Kosovo', 'int_code': 383},
    {'country': 'Croatia', 'int_code': 385},
    {'country': 'Slovenia', 'int_code': 386},
    {'country': 'Bosnia and Herzegovina', 'int_code': 387},
    {'country': 'North Macedonia', 'int_code': 389},
    {'country': 'Italy', 'int_code': 39},
    {'country': 'Romania', 'int_code': 40},
    {'country': 'Switzerland', 'int_code': 41},
    {'country': 'Czech Republic', 'int_code': 420},
    {'country': 'Slovakia', 'int_code': 421},
    {'country': 'Liechtenstein', 'int_code': 423},
    {'country': 'Austria', 'int_code': 43},
    {'country': 'United Kingdom', 'int_code': 44},
    {'country': 'Denmark', 'int_code': 45},
    {'country': 'Sweden', 'int_code': 46},
    {'country': 'Norway', 'int_code': 47},
    {'country': 'Poland', 'int_code': 48},
    {'country': 'Germany', 'int_code': 49},
    {'country': 'Falkland Islands', 'int_code': 500},
    {'country': 'Belize', 'int_code': 501},
    {'country': 'Guatemala', 'int_code': 502},
    {'country': 'El Salvador', 'int_code': 503},
    {'country': 'Honduras', 'int_code': 504},
    {'country': 'Nicaragua', 'int_code': 505},
    {'country': 'Costa Rica', 'int_code': 506},
    {'country': 'Panama', 'int_code': 507},
    {'country': 'Saint-Pierre and Miquelon', 'int_code': 508},
    {'country': 'Haiti', 'int_code': 509},
    {'country': 'Peru', 'int_code': 51},
    {'country': 'Mexico', 'int_code': 52},
    {'country': 'Cuba', 'int_code': 53},
    {'country': 'Argentina', 'int_code': 54},
    {'country': 'Brazil', 'int_code': 55},
    {'country': 'Chile', 'int_code': 56},
    {'country': 'Colombia', 'int_code': 57},
    {'country': 'Venezuela', 'int_code': 58},
    {'country': 'Guadeloupe', 'int_code': 59},
    {'country': 'Bolivia', 'int_code': 591},
    {'country': 'Guyana', 'int_code': 592},
    {'country': 'Ecuador', 'int_code': 593},
    {'country': 'French Guiana', 'int_code': 594},
    {'country': 'Paraguay', 'int_code': 595},
    {'country': 'Martinique', 'int_code': 596},
    {'country': 'Suriname', 'int_code': 597},
    {'country': 'Uruguay', 'int_code': 598},
    {'country': 'Malaysia', 'int_code': 60},
    {'country': 'Australia', 'int_code': 61},
    {'country': 'Indonesia', 'int_code': 62},
    {'country': 'Philippines', 'int_code': 63},
    {'country': 'New Zealand', 'int_code': 64},
    {'country': 'Pitcairn Islands', 'int_code': 65},
    {'country': 'Singapore', 'int_code': 66},
    {'country': 'Thailand', 'int_code': 67},
    {'country': 'East Timor', 'int_code': 670},
    {'country': 'Brunei', 'int_code': 673},
    {'country': 'Nauru', 'int_code': 674},
    {'country': 'Papua New Guinea', 'int_code': 675},
    {'country': 'Tonga', 'int_code': 676},
    {'country': 'Solomon Islands', 'int_code': 677},
    {'country': 'Vanuatu', 'int_code': 678},
    {'country': 'Fiji', 'int_code': 679},
    {'country': 'Palau', 'int_code': 680},
    {'country': 'Wallis and Futuna', 'int_code': 681},
    {'country': 'Cook Islands', 'int_code': 682},
    {'country': 'Niue', 'int_code': 683},
    {'country': 'Samoa', 'int_code': 685},
    {'country': 'Kiribati', 'int_code': 686},
    {'country': 'New Caledonia', 'int_code': 687},
    {'country': 'Tuvalu', 'int_code': 688},
    {'country': 'French Polynesia', 'int_code': 689},
    {'country': 'Tokelau', 'int_code': 690},
    {'country': 'Federated States of Micronesia', 'int_code': 691},
    {'country': 'Marshall Islands', 'int_code': 692},
    {'country': 'Russia', 'int_code': 7},
    {'country': 'Japan', 'int_code': 81},
    {'country': 'South Korea', 'int_code': 82},
    {'country': 'Vietnam', 'int_code': 84},
    {'country': 'North Korea', 'int_code': 850},
    {'country': 'Hong Kong', 'int_code': 852},
    {'country': 'Macau', 'int_code': 853},
    {'country': 'Cambodia', 'int_code': 855},
    {'country': 'Laos', 'int_code': 856},
    {'country': 'China', 'int_code': 86},
    {'country': 'Bangladesh', 'int_code': 880},
    {'country': 'Taiwan', 'int_code': 886},
    {'country': 'Turkey', 'int_code': 90},
    {'country': 'India', 'int_code': 91},
    {'country': 'Pakistan', 'int_code': 92},
    {'country': 'Afghanistan', 'int_code': 93},
    {'country': 'Sri Lanka', 'int_code': 94},
    {'country': 'Myanmar', 'int_code': 95},
    {'country': '{Maldives', 'int_code': 960},
    {'country': 'Lebanon', 'int_code': 961},
    {'country': 'Jordan', 'int_code': 962},
    {'country': 'Syria', 'int_code': 963},
    {'country': 'Iraq', 'int_code': 964},
    {'country': 'Kuwait', 'int_code': 965},
    {'country': 'Saudi Arabia', 'int_code': 966},
    {'country': 'Yemen', 'int_code': 967},
    {'country': 'Oman', 'int_code': 968},
    {'country': 'Palestine', 'int_code': 970},
    {'country': 'United Arab Emirates', 'int_code': 971},
    {'country': 'Israel', 'int_code': 972},
    {'country': 'Bahrain', 'int_code': 973},
    {'country': 'Qatar', 'int_code': 974},
    {'country': 'Bhutan', 'int_code': 975},
    {'country': 'Mongolia', 'int_code': 976},
    {'country': 'Nepal', 'int_code': 977},
    {'country': 'Iran', 'int_code': 98},
    {'country': 'Tajikistan', 'int_code': 992},
    {'country': 'Turkmenistan', 'int_code': 993},
    {'country': 'Azerbaijan', 'int_code': 994},
    {'country': 'Georgia', 'int_code': 995},
    {'country': 'Kyrgyzstan', 'int_code': 996},
    {'country': 'Kazakhstan', 'int_code': 997},
    {'country': 'Uzbekistan', 'int_code': 998}
]
