
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-12T18:53:34+0100",
 "dirty": true,
 "error": null,
 "full-revisionid": "558f33bce8ba1995fe6df5c4446434d6b7a5021d",
 "version": "0.4.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
