# Generated by ariadne-codegen
# Source: resources/ariadne_client_configs/transactions.graphql

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel


class HswapBuyNftTx(BaseModel):
    hswap_buy_nft_tx: "HswapBuyNftTxHswapBuyNftTx" = Field(alias="hswapBuyNftTx")


class HswapBuyNftTxHswapBuyNftTx(BaseModel):
    txs: List["HswapBuyNftTxHswapBuyNftTxTxs"]


class HswapBuyNftTxHswapBuyNftTxTxs(BaseModel):
    last_valid_block_height: Optional[int] = Field(alias="lastValidBlockHeight")
    tx: Optional[Any]
