# Generated by ariadne-codegen
# Source: resources/ariadne_client_configs/transactions.graphql

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel


class HswapSellNftTx(BaseModel):
    hswap_sell_nft_tx: "HswapSellNftTxHswapSellNftTx" = Field(alias="hswapSellNftTx")


class HswapSellNftTxHswapSellNftTx(BaseModel):
    txs: List["HswapSellNftTxHswapSellNftTxTxs"]


class HswapSellNftTxHswapSellNftTxTxs(BaseModel):
    last_valid_block_height: Optional[int] = Field(alias="lastValidBlockHeight")
    tx: Optional[Any]
