# Generated by ariadne-codegen
# Source: resources/ariadne_client_configs/transactions.graphql

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel


class TakeBidTx(BaseModel):
    take_bid_tx: "TakeBidTxTakeBidTx" = Field(alias="takeBidTx")


class TakeBidTxTakeBidTx(BaseModel):
    txs: List["TakeBidTxTakeBidTxTxs"]


class TakeBidTxTakeBidTxTxs(BaseModel):
    last_valid_block_height: Optional[int] = Field(alias="lastValidBlockHeight")
    tx: Optional[Any]
    tx_v_0: Any = Field(alias="txV0")
