# Generated by ariadne-codegen
# Source: resources/ariadne_client_configs/transactions.graphql

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel


class TswapEditSingleListingTx(BaseModel):
    tswap_edit_single_listing_tx: "TswapEditSingleListingTxTswapEditSingleListingTx" = (
        Field(alias="tswapEditSingleListingTx")
    )


class TswapEditSingleListingTxTswapEditSingleListingTx(BaseModel):
    txs: List["TswapEditSingleListingTxTswapEditSingleListingTxTxs"]


class TswapEditSingleListingTxTswapEditSingleListingTxTxs(BaseModel):
    last_valid_block_height: Optional[int] = Field(alias="lastValidBlockHeight")
    tx: Optional[Any]
    tx_v_0: Any = Field(alias="txV0")
