# Generated by ariadne-codegen
# Source: resources/ariadne_client_configs/transactions.graphql

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel


class TswapEditPoolTx(BaseModel):
    tswap_edit_pool_tx: "TswapEditPoolTxTswapEditPoolTx" = Field(
        alias="tswapEditPoolTx"
    )


class TswapEditPoolTxTswapEditPoolTx(BaseModel):
    pool: str
    txs: List["TswapEditPoolTxTswapEditPoolTxTxs"]


class TswapEditPoolTxTswapEditPoolTxTxs(BaseModel):
    last_valid_block_height: Optional[int] = Field(alias="lastValidBlockHeight")
    tx: Optional[Any]
