
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-08T14:05:24-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "48e0c702afc73d8cbb8067c06074b425cb26725f",
 "version": "23.12.00"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
