VERSION_YEAR = 2024
VERSION_MONTH = int('01')
VERSION_DAY = int('09')
VERSION_HOUR = int('16')
VERSION_MINUTE = int('37')
MAJOR_VERSION = 1
MINOR_VERSION = 9
PATCH_VERSION = 202401091637
version_date = '2024/01/09 16:37'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
