
def register_period(teacher:Teacher,period:int,school:School,c:Class): ...
class Teacher:
    name: str
    reason_of_absentee: str
    present: bool
    def __new__(name:str,sub:str,present:bool) -> Teacher: ...
    def add_period(period:int,grade:int,section:str) -> None: ...
    def get_sub() -> str: ...

class Class:
    def __new__(name:str): ...
class School:
    def add_teacher(teacher:Teacher): ...
    def generate_substitutions(): ...
    def add_class(c:Class): ...

    # def teacher_by_subjects(subject:str) -> list: ...