
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-10T17:31:45+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "444f60f8ffafb2113b4b1ebe8502b08576a93976",
 "version": "1.20.0.post0.dev56"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
