# coding: utf-8

"""
    Phrame

    Phrame API  # noqa: E501

    The version of the OpenAPI document: 1.0.4
    Contact: david@3adesign.co.uk
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import PhrameServer
from PhrameServer.api.phrame_api import PhrameApi  # noqa: E501
from PhrameServer.rest import ApiException


class TestPhrameApi(unittest.TestCase):
    """PhrameApi unit test stubs"""

    def setUp(self):
        self.api = PhrameServer.api.phrame_api.PhrameApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_hello_world(self):
        """Test case for get_hello_world

        return \"Hello\" message  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
