# coding: utf-8

"""
    Phrame

    Phrame API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: david@3adesign.co.uk
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import Phrame
from Phrame.models.get_hello_world200_response import GetHelloWorld200Response  # noqa: E501
from Phrame.rest import ApiException

class TestGetHelloWorld200Response(unittest.TestCase):
    """GetHelloWorld200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test GetHelloWorld200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = Phrame.models.get_hello_world200_response.GetHelloWorld200Response()  # noqa: E501
        if include_optional :
            return GetHelloWorld200Response(
                message = ''
            )
        else :
            return GetHelloWorld200Response(
        )

    def testGetHelloWorld200Response(self):
        """Test GetHelloWorld200Response"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
