# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from deepproto.proto.tracepoint.v1 import tracepoint_pb2 as deepproto_dot_proto_dot_tracepoint_dot_v1_dot_tracepoint__pb2


class SnapshotServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.send = channel.unary_unary(
                '/deepproto.proto.tracepoint.v1.SnapshotService/send',
                request_serializer=deepproto_dot_proto_dot_tracepoint_dot_v1_dot_tracepoint__pb2.Snapshot.SerializeToString,
                response_deserializer=deepproto_dot_proto_dot_tracepoint_dot_v1_dot_tracepoint__pb2.SnapshotResponse.FromString,
                )


class SnapshotServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def send(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SnapshotServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'send': grpc.unary_unary_rpc_method_handler(
                    servicer.send,
                    request_deserializer=deepproto_dot_proto_dot_tracepoint_dot_v1_dot_tracepoint__pb2.Snapshot.FromString,
                    response_serializer=deepproto_dot_proto_dot_tracepoint_dot_v1_dot_tracepoint__pb2.SnapshotResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'deepproto.proto.tracepoint.v1.SnapshotService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SnapshotService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def send(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/deepproto.proto.tracepoint.v1.SnapshotService/send',
            deepproto_dot_proto_dot_tracepoint_dot_v1_dot_tracepoint__pb2.Snapshot.SerializeToString,
            deepproto_dot_proto_dot_tracepoint_dot_v1_dot_tracepoint__pb2.SnapshotResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
