
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-11T18:03:28-0500",
 "dirty": true,
 "error": null,
 "full-revisionid": "fb041ae0f234db122a6ed20117ddb19aa9106824",
 "version": "3.20.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
