
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-12T11:18:16-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "b84574f1da79557a7b3852633eddfd7dccd145a9",
 "version": "0.11.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
