
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-13T12:12:55+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "d02da4438878873d0267ec94234843f0056bd1bf",
 "version": "1.0.8rc0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
