
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-10T13:52:02-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "ed0e9f3b97f1bbf04ece0f10af22f0dcb89f629a",
 "version": "2.7.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
