
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-11T14:20:43+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "5441f34b7db518785fb2888ecaabfda480b6ab30",
 "version": "0.56"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
