
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-10T11:14:33+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "a27f9a3ddefaa37cfae4ee6ff98bfe80639c7b61",
 "version": "0.3.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
