# Generated by Django 5.0.1 on 2024-01-09 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('state_id', models.IntegerField(null=True)),
                ('iso', models.CharField(max_length=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zipcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Delegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65)),
                ('delegation_id', models.IntegerField(null=True)),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo_cp_mex.state')),
            ],
        ),
        migrations.CreateModel(
            name='Suburb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65)),
                ('suburb_id', models.IntegerField(null=True)),
                ('delegation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo_cp_mex.delegation')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo_cp_mex.state')),
                ('zipcode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo_cp_mex.zipcode')),
            ],
        ),
    ]
