
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-11T11:24:50+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "e5d9349562c8e0a9e1399df8e4a816de0651e9ba",
 "version": "0.55"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
