# coding: utf-8
# Generated by setup.py for PyCBC on 2024-01-09 11:17:53 +0000.

# general info
version = '2.3.3'
date = '2024-01-09 10:30:12 +0000'
release = 'True'
last_release = '2.4.0'

# git info
git_hash = '132e9da64ef935810eb19ec565703c3689e3236e'
git_branch = 'None'
git_tag = 'v2.3.3'
git_author = 'Ian Harry <ian.harry@ligo.org>'
git_committer = 'GitHub <noreply@github.com>'
git_status = 'CLEAN: All modifications committed'
git_builder = 'Unknown User <>'
git_build_date = '2024-01-09 11:17:53 +0000'
git_verbose_msg = """Version: 2.3.3
Branch: None
Tag: v2.3.3
Id: 132e9da64ef935810eb19ec565703c3689e3236e
Builder: Unknown User <>
Build date: 2024-01-09 11:17:53 +0000
Repository status is CLEAN: All modifications committed"""

from pycbc._version import *
