# Generated by Django 3.2.12 on 2022-03-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stoelindeling', '0002_seat_auto_create'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='seat',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='seat',
            name='seated',
            field=models.BooleanField(default=False, verbose_name='Seated'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='x',
            field=models.IntegerField(default=0, verbose_name='X position'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='y',
            field=models.IntegerField(default=0, verbose_name='Y position'),
        ),
    ]
