# Generated by Django 3.2.12 on 2022-04-06 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chronos', '0010_remove_subject_unique_name_per_site'),
        ('stoelindeling', '0003_seat_negative_x_y'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatingplan',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chronos.subject', verbose_name='Subject'),
        ),
    ]
