# Generated by Django 4.1.5 on 2023-02-26 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0047_add_room_model"),
        ("stoelindeling", "0004_alter_seatingplan_subject"),
    ]

    run_before = [
        ("chronos", "0013_move_room_to_core"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seatingplan",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.room",
                verbose_name="Room",
            ),
        ),
    ]
