
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-14T00:38:52+1100",
 "dirty": false,
 "error": null,
 "full-revisionid": "0e46e15fc80c2d4492d9580f111a768536f6afaa",
 "version": "0.29"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
