
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-11T13:58:39-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "1685ef7b423974c344e12d3c53eb0f0066a4225c",
 "version": "2.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
