
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-10T11:51:44-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "96d995ba6afbb1cd7b4d33956bbae90cfd32adc5",
 "version": "v1.5.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
