# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from spaceone.api.provisioning.v1 import catalog_group_pb2 as spaceone_dot_api_dot_provisioning_dot_v1_dot_catalog__group__pb2


class CatalogGroupStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.create_catalog = channel.unary_unary(
                '/spaceone.api.provisioning.v1.CatalogGroup/create_catalog',
                request_serializer=spaceone_dot_api_dot_provisioning_dot_v1_dot_catalog__group__pb2.CreateCatalogGroupRequest.SerializeToString,
                response_deserializer=spaceone_dot_api_dot_provisioning_dot_v1_dot_catalog__group__pb2.CatalogGroupInfo.FromString,
                )


class CatalogGroupServicer(object):
    """Missing associated documentation comment in .proto file."""

    def create_catalog(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CatalogGroupServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'create_catalog': grpc.unary_unary_rpc_method_handler(
                    servicer.create_catalog,
                    request_deserializer=spaceone_dot_api_dot_provisioning_dot_v1_dot_catalog__group__pb2.CreateCatalogGroupRequest.FromString,
                    response_serializer=spaceone_dot_api_dot_provisioning_dot_v1_dot_catalog__group__pb2.CatalogGroupInfo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'spaceone.api.provisioning.v1.CatalogGroup', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CatalogGroup(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def create_catalog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/spaceone.api.provisioning.v1.CatalogGroup/create_catalog',
            spaceone_dot_api_dot_provisioning_dot_v1_dot_catalog__group__pb2.CreateCatalogGroupRequest.SerializeToString,
            spaceone_dot_api_dot_provisioning_dot_v1_dot_catalog__group__pb2.CatalogGroupInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
