# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: interconnection/handshake/algos/lr.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(interconnection/handshake/algos/lr.proto\x12\x1corg.interconnection.v2.algos\x1a\x19google/protobuf/any.proto\"\xa3\x01\n\x15LrHyperparamsProposal\x12\x1a\n\x12supported_versions\x18\x01 \x03(\x05\x12\x12\n\noptimizers\x18\x02 \x03(\x05\x12\x1b\n\x13last_batch_policies\x18\x03 \x03(\x05\x12\x13\n\x0buse_l0_norm\x18\x04 \x01(\x08\x12\x13\n\x0buse_l1_norm\x18\x05 \x01(\x08\x12\x13\n\x0buse_l2_norm\x18\x06 \x01(\x08\"k\n\x10LrDataIoProposal\x12\x1a\n\x12supported_versions\x18\x01 \x03(\x05\x12\x13\n\x0bsample_size\x18\x02 \x01(\x03\x12\x13\n\x0b\x66\x65\x61ture_num\x18\x03 \x01(\x05\x12\x11\n\thas_label\x18\x04 \x01(\x08\"\xe2\x01\n\x13LrHyperparamsResult\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\x16\n\x0eoptimizer_name\x18\x02 \x01(\x05\x12-\n\x0foptimizer_param\x18\x03 \x01(\x0b\x32\x14.google.protobuf.Any\x12\x11\n\tnum_epoch\x18\x04 \x01(\x03\x12\x12\n\nbatch_size\x18\x05 \x01(\x03\x12\x19\n\x11last_batch_policy\x18\x06 \x01(\x05\x12\x0f\n\x07l0_norm\x18\x07 \x01(\x01\x12\x0f\n\x07l1_norm\x18\x08 \x01(\x01\x12\x0f\n\x07l2_norm\x18\t \x01(\x01\"`\n\x0eLrDataIoResult\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\x13\n\x0bsample_size\x18\x02 \x01(\x03\x12\x14\n\x0c\x66\x65\x61ture_nums\x18\x03 \x03(\x05\x12\x12\n\nlabel_rank\x18\x04 \x01(\x05*S\n\x0fLastBatchPolicy\x12!\n\x1dLAST_BATCH_POLICY_UNSPECIFIED\x10\x00\x12\x1d\n\x19LAST_BATCH_POLICY_DISCARD\x10\x01\x62\x06proto3')

_LASTBATCHPOLICY = DESCRIPTOR.enum_types_by_name['LastBatchPolicy']
LastBatchPolicy = enum_type_wrapper.EnumTypeWrapper(_LASTBATCHPOLICY)
LAST_BATCH_POLICY_UNSPECIFIED = 0
LAST_BATCH_POLICY_DISCARD = 1


_LRHYPERPARAMSPROPOSAL = DESCRIPTOR.message_types_by_name['LrHyperparamsProposal']
_LRDATAIOPROPOSAL = DESCRIPTOR.message_types_by_name['LrDataIoProposal']
_LRHYPERPARAMSRESULT = DESCRIPTOR.message_types_by_name['LrHyperparamsResult']
_LRDATAIORESULT = DESCRIPTOR.message_types_by_name['LrDataIoResult']
LrHyperparamsProposal = _reflection.GeneratedProtocolMessageType('LrHyperparamsProposal', (_message.Message,), {
  'DESCRIPTOR' : _LRHYPERPARAMSPROPOSAL,
  '__module__' : 'interconnection.handshake.algos.lr_pb2'
  # @@protoc_insertion_point(class_scope:org.interconnection.v2.algos.LrHyperparamsProposal)
  })
_sym_db.RegisterMessage(LrHyperparamsProposal)

LrDataIoProposal = _reflection.GeneratedProtocolMessageType('LrDataIoProposal', (_message.Message,), {
  'DESCRIPTOR' : _LRDATAIOPROPOSAL,
  '__module__' : 'interconnection.handshake.algos.lr_pb2'
  # @@protoc_insertion_point(class_scope:org.interconnection.v2.algos.LrDataIoProposal)
  })
_sym_db.RegisterMessage(LrDataIoProposal)

LrHyperparamsResult = _reflection.GeneratedProtocolMessageType('LrHyperparamsResult', (_message.Message,), {
  'DESCRIPTOR' : _LRHYPERPARAMSRESULT,
  '__module__' : 'interconnection.handshake.algos.lr_pb2'
  # @@protoc_insertion_point(class_scope:org.interconnection.v2.algos.LrHyperparamsResult)
  })
_sym_db.RegisterMessage(LrHyperparamsResult)

LrDataIoResult = _reflection.GeneratedProtocolMessageType('LrDataIoResult', (_message.Message,), {
  'DESCRIPTOR' : _LRDATAIORESULT,
  '__module__' : 'interconnection.handshake.algos.lr_pb2'
  # @@protoc_insertion_point(class_scope:org.interconnection.v2.algos.LrDataIoResult)
  })
_sym_db.RegisterMessage(LrDataIoResult)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LASTBATCHPOLICY._serialized_start=703
  _LASTBATCHPOLICY._serialized_end=786
  _LRHYPERPARAMSPROPOSAL._serialized_start=102
  _LRHYPERPARAMSPROPOSAL._serialized_end=265
  _LRDATAIOPROPOSAL._serialized_start=267
  _LRDATAIOPROPOSAL._serialized_end=374
  _LRHYPERPARAMSRESULT._serialized_start=377
  _LRHYPERPARAMSRESULT._serialized_end=603
  _LRDATAIORESULT._serialized_start=605
  _LRDATAIORESULT._serialized_end=701
# @@protoc_insertion_point(module_scope)
