
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-10T11:15:42+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "f56a38f9f19a160ee0928cf791dd94a38ae15ab2",
 "version": "1.14.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
