
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-08T22:20:53-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "3a96f8f319619b4b6fde8a11599645e07fd300c6",
 "version": "0.0.194"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
