'''
## This file is autogenerated from macrosynergy setup.py.

It contains version information for the macrosynergy package.

short_version: 0.1.2

version: 0.1.2

full_version: 0.1.2

git_revision: 223d6f88daf3673f36c9c26772d3951e27d7f610

release: True

'''
short_version: str = '0.1.2'
version: str = '0.1.2'
full_version: str = '0.1.2'
git_revision: str = '223d6f88daf3673f36c9c26772d3951e27d7f610'
release: bool = True
if not release:
    version = full_version
