# Generated by ariadne-codegen
# Source: resources/ariadne_client_configs/collection_data.graphql

from typing import List

from .base_model import BaseModel


class Mints(BaseModel):
    mints: List["MintsMints"]


class MintsMints(BaseModel):
    slug: str
