# Generated by ariadne-codegen
# Source: resources/ariadne_client_configs/collection_data.graphql

from pydantic import Field

from .base_model import BaseModel


class RefreshRarities(BaseModel):
    refresh_rarities: bool = Field(alias="refreshRarities")
