# Generated by ariadne-codegen
# Source: resources/ariadne_client_configs/transactions.graphql

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel


class TswapListNftTx(BaseModel):
    tswap_list_nft_tx: "TswapListNftTxTswapListNftTx" = Field(alias="tswapListNftTx")


class TswapListNftTxTswapListNftTx(BaseModel):
    txs: List["TswapListNftTxTswapListNftTxTxs"]


class TswapListNftTxTswapListNftTxTxs(BaseModel):
    last_valid_block_height: Optional[int] = Field(alias="lastValidBlockHeight")
    tx: Optional[Any]
    tx_v_0: Any = Field(alias="txV0")
