# Generated by ariadne-codegen
# Source: resources/ariadne_client_configs/transactions.graphql

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel


class TswapDepositWithdrawSolTx(BaseModel):
    tswap_deposit_withdraw_sol_tx: "TswapDepositWithdrawSolTxTswapDepositWithdrawSolTx" = Field(
        alias="tswapDepositWithdrawSolTx"
    )


class TswapDepositWithdrawSolTxTswapDepositWithdrawSolTx(BaseModel):
    txs: List["TswapDepositWithdrawSolTxTswapDepositWithdrawSolTxTxs"]


class TswapDepositWithdrawSolTxTswapDepositWithdrawSolTxTxs(BaseModel):
    last_valid_block_height: Optional[int] = Field(alias="lastValidBlockHeight")
    tx: Optional[Any]
