
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-12-23T14:42:15-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "5b04848aeeb911ffa774c8a5eb396e1f65047f5b",
 "version": "0.4.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
