
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-12T15:23:24+0100",
 "dirty": true,
 "error": null,
 "full-revisionid": "801ae9518a6cb4f6f20e6ab14c98a438a258a406",
 "version": "0.5.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
