
# This file was generated by 'versioneer.py' (0.29+8.gf9bbd1b) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-09T19:08:26+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "d4b4ea82e0c4b12827a739a61b9a67a777fd6e55",
 "version": "0.59.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
