# coding: utf-8

"""
    EmployeeEFCrud

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from EFCrud.api.employees_api import EmployeesApi


class TestEmployeesApi(unittest.TestCase):
    """EmployeesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EmployeesApi()

    def tearDown(self) -> None:
        pass

    def test_api_employees_get(self) -> None:
        """Test case for api_employees_get

        """
        pass

    def test_api_employees_id_delete(self) -> None:
        """Test case for api_employees_id_delete

        """
        pass

    def test_api_employees_id_get(self) -> None:
        """Test case for api_employees_id_get

        """
        pass

    def test_api_employees_id_put(self) -> None:
        """Test case for api_employees_id_put

        """
        pass

    def test_api_employees_post(self) -> None:
        """Test case for api_employees_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
