# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.


import collections

from sys import version_info as _version_info
if _version_info < (3, 7, 0):
    raise RuntimeError("Python 3.7 or later required")

from . import _ITKCommonPython


from . import _TubeTKPython



from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _tubeCropTubesPython
else:
    import _tubeCropTubesPython

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

_swig_new_instance_method = _tubeCropTubesPython.SWIG_PyInstanceMethod_New
_swig_new_static_method = _tubeCropTubesPython.SWIG_PyStaticMethod_New

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


import collections.abc
import itk.ITKCommonBasePython
import itk.itkMatrixPython
import itk.itkVectorPython
import itk.vnl_vector_refPython
import itk.stdcomplexPython
import itk.pyBasePython
import itk.vnl_vectorPython
import itk.vnl_matrixPython
import itk.itkFixedArrayPython
import itk.vnl_matrix_fixedPython
import itk.itkPointPython
import itk.itkCovariantVectorPython
import itk.itkGroupSpatialObjectPython
import itk.itkSpatialObjectBasePython
import itk.itkBoundingBoxPython
import itk.itkVectorContainerPython
import itk.itkContinuousIndexPython
import itk.itkIndexPython
import itk.itkSizePython
import itk.itkOffsetPython
import itk.itkArrayPython
import itk.itkMapContainerPython
import itk.itkAffineTransformPython
import itk.itkTransformBasePython
import itk.itkOptimizerParametersPython
import itk.itkDiffusionTensor3DPython
import itk.itkSymmetricSecondRankTensorPython
import itk.itkVariableLengthVectorPython
import itk.itkArray2DPython
import itk.itkMatrixOffsetTransformBasePython
import itk.itkImageRegionPython
import itk.itkSpatialObjectPropertyPython
import itk.itkRGBAPixelPython
import itk.itkImagePython
import itk.itkRGBPixelPython

def tubeCropTubes2_New():
    return tubeCropTubes2.New()

class tubeCropTubes2(itk.ITKCommonBasePython.itkProcessObject):
    r"""Proxy of C++ tubeCropTubes2 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_tubeCropTubesPython.tubeCropTubes2___New_orig__)
    Clone = _swig_new_instance_method(_tubeCropTubesPython.tubeCropTubes2_Clone)
    SetInput = _swig_new_instance_method(_tubeCropTubesPython.tubeCropTubes2_SetInput)
    GetInput = _swig_new_instance_method(_tubeCropTubesPython.tubeCropTubes2_GetInput)
    SetBoxPositionInWorldSpace = _swig_new_instance_method(_tubeCropTubesPython.tubeCropTubes2_SetBoxPositionInWorldSpace)
    GetBoxPositionInWorldSpace = _swig_new_instance_method(_tubeCropTubesPython.tubeCropTubes2_GetBoxPositionInWorldSpace)
    SetBoxSizeInWorldSpace = _swig_new_instance_method(_tubeCropTubesPython.tubeCropTubes2_SetBoxSizeInWorldSpace)
    GetBoxSizeInWorldSpace = _swig_new_instance_method(_tubeCropTubesPython.tubeCropTubes2_GetBoxSizeInWorldSpace)
    SetMaskImage = _swig_new_instance_method(_tubeCropTubesPython.tubeCropTubes2_SetMaskImage)
    GetMaskImage = _swig_new_instance_method(_tubeCropTubesPython.tubeCropTubes2_GetMaskImage)
    SetUseMaskImage = _swig_new_instance_method(_tubeCropTubesPython.tubeCropTubes2_SetUseMaskImage)
    GetUseMaskImage = _swig_new_instance_method(_tubeCropTubesPython.tubeCropTubes2_GetUseMaskImage)
    SetCropTubes = _swig_new_instance_method(_tubeCropTubesPython.tubeCropTubes2_SetCropTubes)
    GetCropTubes = _swig_new_instance_method(_tubeCropTubesPython.tubeCropTubes2_GetCropTubes)
    GetOutput = _swig_new_instance_method(_tubeCropTubesPython.tubeCropTubes2_GetOutput)
    __swig_destroy__ = _tubeCropTubesPython.delete_tubeCropTubes2
    cast = _swig_new_static_method(_tubeCropTubesPython.tubeCropTubes2_cast)

    def New(*args, **kargs):
        """New() -> tubeCropTubes2

        Create a new object of the class tubeCropTubes2 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          tubeCropTubes2.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = tubeCropTubes2.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = tubeCropTubes2.__New_orig__()
        from itk.support import template_class
        template_class.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register tubeCropTubes2 in _tubeCropTubesPython:
_tubeCropTubesPython.tubeCropTubes2_swigregister(tubeCropTubes2)
tubeCropTubes2___New_orig__ = _tubeCropTubesPython.tubeCropTubes2___New_orig__
tubeCropTubes2_cast = _tubeCropTubesPython.tubeCropTubes2_cast


def tubeCropTubes3_New():
    return tubeCropTubes3.New()

class tubeCropTubes3(itk.ITKCommonBasePython.itkProcessObject):
    r"""Proxy of C++ tubeCropTubes3 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_tubeCropTubesPython.tubeCropTubes3___New_orig__)
    Clone = _swig_new_instance_method(_tubeCropTubesPython.tubeCropTubes3_Clone)
    SetInput = _swig_new_instance_method(_tubeCropTubesPython.tubeCropTubes3_SetInput)
    GetInput = _swig_new_instance_method(_tubeCropTubesPython.tubeCropTubes3_GetInput)
    SetBoxPositionInWorldSpace = _swig_new_instance_method(_tubeCropTubesPython.tubeCropTubes3_SetBoxPositionInWorldSpace)
    GetBoxPositionInWorldSpace = _swig_new_instance_method(_tubeCropTubesPython.tubeCropTubes3_GetBoxPositionInWorldSpace)
    SetBoxSizeInWorldSpace = _swig_new_instance_method(_tubeCropTubesPython.tubeCropTubes3_SetBoxSizeInWorldSpace)
    GetBoxSizeInWorldSpace = _swig_new_instance_method(_tubeCropTubesPython.tubeCropTubes3_GetBoxSizeInWorldSpace)
    SetMaskImage = _swig_new_instance_method(_tubeCropTubesPython.tubeCropTubes3_SetMaskImage)
    GetMaskImage = _swig_new_instance_method(_tubeCropTubesPython.tubeCropTubes3_GetMaskImage)
    SetUseMaskImage = _swig_new_instance_method(_tubeCropTubesPython.tubeCropTubes3_SetUseMaskImage)
    GetUseMaskImage = _swig_new_instance_method(_tubeCropTubesPython.tubeCropTubes3_GetUseMaskImage)
    SetCropTubes = _swig_new_instance_method(_tubeCropTubesPython.tubeCropTubes3_SetCropTubes)
    GetCropTubes = _swig_new_instance_method(_tubeCropTubesPython.tubeCropTubes3_GetCropTubes)
    GetOutput = _swig_new_instance_method(_tubeCropTubesPython.tubeCropTubes3_GetOutput)
    __swig_destroy__ = _tubeCropTubesPython.delete_tubeCropTubes3
    cast = _swig_new_static_method(_tubeCropTubesPython.tubeCropTubes3_cast)

    def New(*args, **kargs):
        """New() -> tubeCropTubes3

        Create a new object of the class tubeCropTubes3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          tubeCropTubes3.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = tubeCropTubes3.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = tubeCropTubes3.__New_orig__()
        from itk.support import template_class
        template_class.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register tubeCropTubes3 in _tubeCropTubesPython:
_tubeCropTubesPython.tubeCropTubes3_swigregister(tubeCropTubes3)
tubeCropTubes3___New_orig__ = _tubeCropTubesPython.tubeCropTubes3___New_orig__
tubeCropTubes3_cast = _tubeCropTubesPython.tubeCropTubes3_cast


def tubeCropTubes4_New():
    return tubeCropTubes4.New()

class tubeCropTubes4(itk.ITKCommonBasePython.itkProcessObject):
    r"""Proxy of C++ tubeCropTubes4 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_tubeCropTubesPython.tubeCropTubes4___New_orig__)
    Clone = _swig_new_instance_method(_tubeCropTubesPython.tubeCropTubes4_Clone)
    SetInput = _swig_new_instance_method(_tubeCropTubesPython.tubeCropTubes4_SetInput)
    GetInput = _swig_new_instance_method(_tubeCropTubesPython.tubeCropTubes4_GetInput)
    SetBoxPositionInWorldSpace = _swig_new_instance_method(_tubeCropTubesPython.tubeCropTubes4_SetBoxPositionInWorldSpace)
    GetBoxPositionInWorldSpace = _swig_new_instance_method(_tubeCropTubesPython.tubeCropTubes4_GetBoxPositionInWorldSpace)
    SetBoxSizeInWorldSpace = _swig_new_instance_method(_tubeCropTubesPython.tubeCropTubes4_SetBoxSizeInWorldSpace)
    GetBoxSizeInWorldSpace = _swig_new_instance_method(_tubeCropTubesPython.tubeCropTubes4_GetBoxSizeInWorldSpace)
    SetMaskImage = _swig_new_instance_method(_tubeCropTubesPython.tubeCropTubes4_SetMaskImage)
    GetMaskImage = _swig_new_instance_method(_tubeCropTubesPython.tubeCropTubes4_GetMaskImage)
    SetUseMaskImage = _swig_new_instance_method(_tubeCropTubesPython.tubeCropTubes4_SetUseMaskImage)
    GetUseMaskImage = _swig_new_instance_method(_tubeCropTubesPython.tubeCropTubes4_GetUseMaskImage)
    SetCropTubes = _swig_new_instance_method(_tubeCropTubesPython.tubeCropTubes4_SetCropTubes)
    GetCropTubes = _swig_new_instance_method(_tubeCropTubesPython.tubeCropTubes4_GetCropTubes)
    GetOutput = _swig_new_instance_method(_tubeCropTubesPython.tubeCropTubes4_GetOutput)
    __swig_destroy__ = _tubeCropTubesPython.delete_tubeCropTubes4
    cast = _swig_new_static_method(_tubeCropTubesPython.tubeCropTubes4_cast)

    def New(*args, **kargs):
        """New() -> tubeCropTubes4

        Create a new object of the class tubeCropTubes4 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          tubeCropTubes4.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = tubeCropTubes4.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = tubeCropTubes4.__New_orig__()
        from itk.support import template_class
        template_class.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register tubeCropTubes4 in _tubeCropTubesPython:
_tubeCropTubesPython.tubeCropTubes4_swigregister(tubeCropTubes4)
tubeCropTubes4___New_orig__ = _tubeCropTubesPython.tubeCropTubes4___New_orig__
tubeCropTubes4_cast = _tubeCropTubesPython.tubeCropTubes4_cast


from itk.support import helpers
import itk.support.types as itkt
from typing import Sequence, Tuple, Union

@helpers.accept_array_like_xarray_torch
def crop_tubes(*args,  box_position_in_world_space: Sequence[float]=..., box_size_in_world_space: Sequence[float]=..., mask_image: itkt.Image=..., use_mask_image: bool=..., crop_tubes: bool=...,**kwargs):
    """Functional interface for CropTubes"""
    import itk

    kwarg_typehints = { 'box_position_in_world_space':box_position_in_world_space,'box_size_in_world_space':box_size_in_world_space,'mask_image':mask_image,'use_mask_image':use_mask_image,'crop_tubes':crop_tubes }
    specified_kwarg_typehints = { k:v for (k,v) in kwarg_typehints.items() if kwarg_typehints[k] is not ... }
    kwargs.update(specified_kwarg_typehints)


    instance = itk.CropTubes.New(*args, **kwargs)

    return instance.__internal_call__()

def crop_tubes_init_docstring():
    import itk
    from itk.support import template_class

    filter_class = itk.TubeTK.CropTubes
    crop_tubes.process_object = filter_class
    is_template = isinstance(filter_class, template_class.itkTemplate)
    if is_template:
        filter_object = filter_class.values()[0]
    else:
        filter_object = filter_class

    crop_tubes.__doc__ = filter_object.__doc__




