
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-10T11:01:18+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "e772289ab9ce70dc4190de778047fa6d64830161",
 "version": "1.8.19"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
