
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-11T21:54:21+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "e4c892c5ea9b459ac60c70ce82db73a0b0a9adfa",
 "version": "0.8.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
