
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-10T13:48:37+0900",
 "dirty": false,
 "error": null,
 "full-revisionid": "0c5b110a8983867c697c7e6ae6b24ba650702121",
 "version": "1.41.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
