
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-10T10:51:04-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "cc4573fdfa565b201096be76f387ddd8c310ff19",
 "version": "2024.1.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
