# Autogenerated by devscripts/update-version.py

__version__ = '2024.01.08.232709'

RELEASE_GIT_HEAD = '5af1f19787f7d652fce72dd3ab9536cdd980fe85'

VARIANT = 'pip'

UPDATE_HINT = 'You installed yt-dlp with pip or using the wheel from PyPi; Use that to update'

CHANNEL = 'nightly'

ORIGIN = 'yt-dlp/yt-dlp-nightly-builds'

_pkg_version = '2024.01.08.232709dev'
