
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-11T14:05:34+0100",
 "dirty": true,
 "error": null,
 "full-revisionid": "13a199edfb4e24c556ee2cb07454497b59514663",
 "version": "0.4.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
