from setuptools import setup

setup(
    name         = 'jobbot_algos',
    author       = 'mrtweety123',
    author_email = 'mrtweety123@proton.me',
    version      = '0.0.7',
    url          = 'https://gitlab.com/jobbot_project/jobbot_algos',
    license      = 'Apache License 2.0',
    packages     = ['jobbot_algos'],
    install_requires = ['setuptools', 'twine', 'pandas', 'loguru', 'fastcore', 'numpy'], # <-- DO NOT EDIT, THIS LINE IS AUTOGENERATED
    description          = 'No description',
    package_dir          = {"jobbot_algos":"lib"},
    include_package_data = True,
    keywords             = ['tag1','tag2']
) 
