VERSION_YEAR = 2024
VERSION_MONTH = int('01')
VERSION_DAY = int('12')
VERSION_HOUR = int('11')
VERSION_MINUTE = int('35')
MAJOR_VERSION = 1
MINOR_VERSION = 10
PATCH_VERSION = 202401121135
version_date = '2024/01/12 11:35'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
