
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-12T08:12:09-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "83331602951804a860fc224e1ff36c124d51c980",
 "version": "0.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
