
""" Data Loading Strategy """
DTA_LOAD_SGY_INSERT = 'Insert'
DTA_LOAD_SGY_UPDATE_INSERT = 'Update / Insert'
DTA_LOAD_SGY_UPDATE = 'Update'
DTA_LOAD_SGY_DELETE_INSERT = 'Delete / Insert'
DTA_LOAD_SGY_FULL_REPLACE = 'Full Replace'
DTA_LOAD_SGY_DELETE = 'Delete'

""" Data Loading Execution Type """
DTA_LOAD_EXEC_TYPE_FULL="FULL"
DTA_LOAD_EXEC_TYPE_RECOVERY="REC"
DTA_LOAD_EXEC_TYPE_DELTA="DLT"
DTA_LOAD_EXEC_TYPE_RECOVERY_DELTA="REC-DLT"
DTA_LOAD_EXEC_TYPE_UNIT="UNIT"