
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-11T20:07:22+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "cdfafc7721fd977e12a844b6dc13b14f7ea660b4",
 "version": "1.20.0.post0.dev58"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
