
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-01-13T15:22:36+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "b7fc66e4a0d5ef81b5ce5f573c76af6355c53491",
 "version": "0.99.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
